lada_kesseler:
  name: Lada Kesseler
  github: lexler
llewellyn_falco:
  name: Llewellyn Falco
  github: isidore
ivett_ordog:
  name: Ivett Ördög
  github: devill
  url: https://ivettordog.com
nitsan_avni:
  name: Nitsan Avni
  github: nitsanavni
steve_kuo:
  name: Steve Kuo
  github: kuoman
